feat: update release script

diff --git a/.x-cmd/release b/.x-cmd/release
--- a/.x-cmd/release
+++ b/.x-cmd/release
@@ -1,14 +1,21 @@
 # shellcheck    shell=sh        disable=SC3043,2034,2154,2030,2031
 
+WSROOT="$(x wsroot)"
 upload_completion(){
     # local version="v0.0.1"
     local release_id="146180286"
     local owner_repo="x-cmd-build/completion"
-    x:info "Clone repo x-cmd-build/completion"
-    [ -d "completion" ] || x gh cl x-cmd-build/completion
     (
-        x cd completion
-        git pull origin main || return 1
+        cd "${WSROOT}" || return 1
+        [ -d zsh-completion ] || {
+            x:error "zsh-completion not found"
+            return 1
+        }
+        [ -d bash-completion ] || {
+            x:error "bash-completion not found"
+            return 1
+        }
+
         x z zsh-completion.tar.xz  zsh-completion
         x z bash-completion.tar.xz bash-completion
         x gh repo release asset ls --release_id "${release_id}" --repo "${owner_repo}" \
@@ -18,8 +25,8 @@ upload_completion(){
                 return 1
             }
         done
-        x gh repo release attachment upload --release_id "${release_id}" --repo "${owner_repo}" zsh-completion.tar.xz
-        x gh repo release attachment upload --release_id "${release_id}" --repo "${owner_repo}" bash-completion.tar.xz
+        x gh repo release asset upload --release_id "${release_id}" --repo "${owner_repo}" zsh-completion.tar.xz
+        x gh repo release asset upload --release_id "${release_id}" --repo "${owner_repo}" bash-completion.tar.xz
     )
 }
 
